/* Colonaid — Singapore low-residue food database
   n:   names [en, zh, ms, ta]
   m:   where it fits — b breakfast, l lunch, d dinner, s snack, k drink (low-residue days), c OK in clear-liquid phase
   cu:  cuisine — c Chinese, m Malay, i Indian, w Western, x any
   t:   content tags used for diet preference / allergy filtering
   r:   "ok" | "avoid" | a hospital rule key from hospitals.js (resolved per hospital)
   mod: preparation tips (keys into i18n "mod.*")
   why: reason key for avoid items (keys into i18n "why.*")
   Sources: SKH, CGH, Parkway sheets; dietitian responses (SCS, Parkway East, workgroup dietitian); research pack tab 6. */

window.CA_FOODS = [
  // ---------- breakfast / light meals ----------
  { id: "kayatoast", c: "local", n: ["Kaya toast (white bread)", "咖椰吐司(白面包)", "Roti bakar kaya (roti putih)", "காயா டோஸ்ட் (வெள்ளை ரொட்டி)"], m: "bs", cu: "cm", t: ["egg", "coconut", "gluten"], r: "kaya" },
  { id: "eggtoast", c: "local", n: ["Soft-boiled eggs with white toast", "半生熟鸡蛋配白吐司", "Telur separuh masak dengan roti bakar putih", "அரை வேக்காட்டு முட்டை, வெள்ளை டோஸ்ட்"], m: "bs", cu: "cmw", t: ["egg", "gluten"], r: "ok" },
  { id: "scrambled", c: "", n: ["Scrambled eggs on white toast", "炒蛋配白吐司", "Telur hancur atas roti bakar putih", "வெள்ளை டோஸ்டில் முட்டைப் பொரியல்"], m: "bl", cu: "w", t: ["egg", "gluten"], r: "eggstyle" },
  { id: "fishcongee", c: "local", n: ["Fish porridge (sliced fish, white rice)", "鱼片粥", "Bubur ikan (hirisan ikan, nasi putih)", "மீன் கஞ்சி (வெள்ளை அரிசி)"], m: "bld", cu: "c", t: ["fish"], r: "ok", mod: ["nogarnish"] },
  { id: "chickencongee", c: "local", n: ["Chicken porridge", "鸡肉粥", "Bubur ayam", "கோழிக் கஞ்சி"], m: "bld", cu: "cm", t: ["chicken"], r: "ok", mod: ["nogarnish"] },
  { id: "eggcongee", c: "", n: ["White porridge with steamed egg", "白粥配蒸蛋", "Bubur putih dengan telur kukus", "வெள்ளைக் கஞ்சி, ஆவியில் வேகவைத்த முட்டை"], m: "bld", cu: "c", t: ["egg"], r: "ok" },
  { id: "tofucongee", c: "", n: ["White porridge with silken tofu", "白粥配嫩豆腐", "Bubur putih dengan tauhu lembut", "வெள்ளைக் கஞ்சி, மென்மையான டோஃபு"], m: "bld", cu: "c", t: ["soy"], r: "ok" },
  { id: "idli", c: "grains", n: ["Idli", "印度蒸米糕 Idli", "Idli", "இட்லி"], m: "bld", cu: "i", t: [], r: "ok", mod: ["nosambar"] },
  { id: "thosai", c: "grains", n: ["Thosai (plain)", "原味印度薄饼 Thosai", "Tosai kosong", "வெற்று தோசை"], m: "bld", cu: "i", t: [], r: "ok", mod: ["nosambar"] },
  { id: "putumayam", c: "grains", n: ["Iddiyappam / putu mayam", "印度米线糕 Putu mayam", "Idiyappam / putu mayam", "இடியாப்பம் / புட்டு மாயம்"], m: "bs", cu: "im", t: [], r: "ok", mod: ["nococonut"] },
  { id: "cornflakes", c: "grains", n: ["Plain cornflakes / rice cereal", "原味玉米片/米片", "Cornflakes / bijirin beras kosong", "சாதா கார்ன்ஃப்ளேக்ஸ் / அரிசி தானியம்"], m: "bs", cu: "w", t: ["gluten"], r: "cereal", mod: ["milkifallowed"] },
  { id: "chweekueh", c: "local", n: ["Chwee kueh", "水粿", "Chwee kueh", "சுவீ குவே"], m: "bs", cu: "c", t: [], r: "chweekueh", mod: ["nochaipoh"] },
  { id: "yoghurt", c: "dairy", n: ["Plain yoghurt", "原味酸奶", "Yogurt kosong", "சாதா தயிர்"], m: "s", cu: "x", t: ["dairy"], r: "dairy", mod: ["smallportion"] },
  { id: "pbtoast", c: "", n: ["White toast with a thin layer of smooth peanut butter", "白吐司抹薄层顺滑花生酱", "Roti bakar putih dengan sapuan nipis mentega kacang licin", "வெள்ளை டோஸ்டில் மெல்லிய மென்மையான பீனட் பட்டர்"], m: "bs", cu: "w", t: ["nut", "gluten"], r: "smoothnut" },

  // ---------- lunch / dinner ----------
  { id: "chickenrice", c: "local", n: ["Steamed chicken rice (skinless)", "白斩鸡饭(去皮)", "Nasi ayam kukus (tanpa kulit)", "ஆவியில் வேகவைத்த கோழி சோறு (தோல் இல்லாமல்)"], m: "ld", cu: "cm", t: ["chicken"], r: "ok", mod: ["nocucumber", "nochilli"] },
  { id: "fishsoup", c: "local", n: ["Sliced fish soup with bee hoon", "鱼片米粉汤", "Sup ikan dengan bihun", "மீன் சூப், பீஹூன்"], m: "ld", cu: "c", t: ["fish"], r: "ok", mod: ["noveg", "nogarnish"] },
  { id: "steamedfish", c: "", n: ["Steamed fish with white rice and light soy sauce", "清蒸鱼配白饭", "Ikan kukus dengan nasi putih dan kicap cair", "ஆவியில் வேகவைத்த மீன், வெள்ளைச் சோறு"], m: "ld", cu: "cm", t: ["fish"], r: "ok", mod: ["nogarnish"] },
  { id: "sotoayam", c: "local", n: ["Soto ayam — clear soup, chicken and bee hoon only", "马来鸡汤米粉(只要清汤、鸡肉、米粉)", "Soto ayam — sup jernih, ayam dan bihun sahaja", "சோட்டோ அயம் — தெளிந்த சூப், கோழி, பீஹூன் மட்டும்"], m: "ld", cu: "m", t: ["chicken"], r: "sotomod", mod: ["nobeansprout", "nogarnish", "nochilli"] },
  { id: "noodlesoup", c: "local", n: ["Egg noodle soup with fish balls", "鱼丸蛋面汤", "Mi sup dengan bebola ikan", "மீன் உருண்டை முட்டை நூடுல் சூப்"], m: "ld", cu: "c", t: ["fish", "egg", "gluten"], r: "ok", mod: ["noveg", "nogarnish"] },
  { id: "meesua", c: "local", n: ["Mee sua soup with fish slices", "鱼片面线汤", "Sup mee sua dengan hirisan ikan", "மீன் துண்டுகளுடன் மீ சுவா சூப்"], m: "ld", cu: "c", t: ["fish", "gluten"], r: "ok", mod: ["noveg", "nogarnish"] },
  { id: "kwayteow", c: "local", n: ["Kway teow soup with fish slices", "鱼片粿条汤", "Kuey teow sup ikan", "மீன் குவே தியாவ் சூப்"], m: "ld", cu: "c", t: ["fish"], r: "ok", mod: ["noveg", "nogarnish"] },
  { id: "bcmsoup", c: "local", n: ["Minced pork noodle soup (no mushrooms, no chilli)", "肉脞面汤(不要香菇、辣椒)", "Mi sup daging babi cincang (tanpa cendawan, tanpa cili)", "பன்றி இறைச்சி நூடுல் சூப் (காளான், மிளகாய் இல்லாமல்)"], m: "ld", cu: "c", t: ["pork", "gluten"], r: "ok", mod: ["noveg", "nogarnish"] },
  { id: "prawnbeehoon", c: "local", n: ["Prawn bee hoon soup", "虾米粉汤", "Sup bihun udang", "இறால் பீஹூன் சூப்"], m: "ld", cu: "cm", t: ["shellfish"], r: "ok", mod: ["noveg", "nogarnish"] },
  { id: "steamedegg", c: "", n: ["Steamed egg custard with white rice", "蒸蛋配白饭", "Telur kukus dengan nasi putih", "ஆவியில் வேகவைத்த முட்டை, வெள்ளைச் சோறு"], m: "ld", cu: "c", t: ["egg"], r: "ok", mod: ["nogarnish"] },
  { id: "tofurice", c: "", n: ["Braised plain tofu or taukwa with white rice", "卤豆腐/豆干配白饭", "Tauhu atau taukwa rebus dengan nasi putih", "டோஃபு / தவ்க்வா, வெள்ளைச் சோறு"], m: "ld", cu: "cm", t: ["soy"], r: "ok", mod: ["nostuffed"] },
  { id: "mockmeat", c: "protein", n: ["Vegetarian mock meat", "素肉", "Daging tiruan vegetarian", "சைவ மாற்று இறைச்சி"], m: "ld", cu: "c", t: ["soy", "gluten"], r: "ok", mod: ["noveg"] },
  { id: "pastachicken", c: "", n: ["White pasta with chicken in a light clear sauce", "白意面配鸡肉(清淡酱汁)", "Pasta putih dengan ayam, sos ringan", "கோழியுடன் வெள்ளை பாஸ்தா (லேசான சாஸ்)"], m: "ld", cu: "w", t: ["chicken", "gluten"], r: "ok", mod: ["noherbs"] },
  { id: "pastacheese", c: "", n: ["White pasta with butter and a little cheese", "黄油少许奶酪白意面", "Pasta putih dengan mentega dan sedikit keju", "வெண்ணெய், சிறிது சீஸுடன் வெள்ளை பாஸ்தா"], m: "ld", cu: "w", t: ["dairy", "gluten"], r: "dairy", mod: ["smallportion"] },
  { id: "pastaoil", c: "", n: ["White pasta with olive oil and salt", "橄榄油白意面", "Pasta putih dengan minyak zaitun", "ஆலிவ் எண்ணெயுடன் வெள்ளை பாஸ்தா"], m: "ld", cu: "w", t: ["gluten"], r: "ok", mod: ["noherbs"] },
  { id: "ricetofuegg", c: "", n: ["White rice with tofu and egg omelette", "白饭配豆腐和煎蛋", "Nasi putih dengan tauhu dan telur dadar", "வெள்ளைச் சோறு, டோஃபு, ஆம்லெட்"], m: "ld", cu: "cmi", t: ["soy", "egg"], r: "eggstyle", mod: ["noonion"] },
  { id: "potatofish", c: "", n: ["Mashed peeled potato with steamed fish", "去皮土豆泥配蒸鱼", "Kentang lenyek (dikupas) dengan ikan kukus", "தோல் நீக்கிய உருளைக்கிழங்கு மசியல், மீன்"], m: "ld", cu: "w", t: ["fish"], r: "potato" },
  { id: "potatotofu", c: "", n: ["Mashed peeled potato with tofu", "去皮土豆泥配豆腐", "Kentang lenyek (dikupas) dengan tauhu", "தோல் நீக்கிய உருளைக்கிழங்கு மசியல், டோஃபு"], m: "ld", cu: "wi", t: ["soy"], r: "potato" },
  { id: "curdrice", c: "local", n: ["Curd rice (no mustard seeds, curry leaves or pomegranate)", "印度酸奶饭(不加芥末籽、咖喱叶)", "Nasi dadih (tanpa biji sawi, daun kari)", "தயிர் சாதம் (கடுகு, கறிவேப்பிலை இல்லாமல்)"], m: "ld", cu: "i", t: ["dairy"], r: "dairy" },
  { id: "chickenporridgemalay", c: "local", n: ["Nasi kosong with ayam masak kicap (no chilli)", "白饭配酱油鸡(不辣)", "Nasi putih dengan ayam masak kicap (tanpa cili)", "வெள்ளைச் சோறு, சோயா சாஸ் கோழி (மிளகாய் இல்லாமல்)"], m: "ld", cu: "m", t: ["chicken"], r: "ok", mod: ["noonion", "nochilli"] },
  { id: "leanbeef", c: "", n: ["Small lean cut of beef, well cooked", "少量瘦牛肉(煮软)", "Sedikit daging lembu tanpa lemak, dimasak lembut", "சிறிய அளவு கொழுப்பற்ற மாட்டிறைச்சி"], m: "ld", cu: "w", t: ["beef", "meat"], r: "redmeat" },
  { id: "strainedvegsoup", c: "veg", n: ["Strained vegetable soup (no bits)", "过滤蔬菜汤(无渣)", "Sup sayur yang ditapis (tanpa sisa)", "வடிகட்டிய காய்கறி சூப் (துண்டுகள் இல்லாமல்)"], m: "ld", cu: "x", t: [], r: "strainedvegsoup" },
  { id: "cookedveg", c: "veg", n: ["Well-cooked peeled vegetables, no seeds", "去皮去籽、煮烂的蔬菜", "Sayur dikupas, dimasak lembut, tanpa biji", "தோல், விதை நீக்கி நன்கு வேகவைத்த காய்கறிகள்"], m: "ld", cu: "x", t: [], r: "cookedveg" },
  { id: "mushroom", c: "veg", n: ["Mushrooms", "蘑菇 / 香菇", "Cendawan", "காளான்"], m: "", cu: "x", t: [], r: "mushroom", why: "fibre" },
  { id: "banana", c: "fruit", n: ["Small ripe banana", "小熟香蕉", "Pisang masak kecil", "சிறிய பழுத்த வாழைப்பழம்"], m: "s", cu: "x", t: [], r: "banana" },

  // ---------- snacks / desserts ----------
  { id: "biscuits", c: "grains", n: ["Plain biscuits (refined, no wholegrain)", "原味饼干(精制,非全麦)", "Biskut kosong (ditapis, bukan bijirin penuh)", "சாதா பிஸ்கட் (முழு தானியம் அல்ல)"], m: "s", cu: "x", t: ["gluten"], r: "ok" },
  { id: "jelly", c: "snacks", n: ["Agar-agar / clear jelly (no fruit pieces)", "燕菜/透明果冻(无果粒)", "Agar-agar / jeli jernih (tanpa buah)", "அகர்-அகர் / தெளிவான ஜெல்லி (பழத் துண்டுகள் இல்லாமல்)"], m: "sc", cu: "x", t: [], r: "jelly", mod: ["nored"] },
  { id: "tauhuay", c: "snacks", n: ["Tau huay (soya bean curd)", "豆花", "Tau huay (tauhu soya)", "டவ் ஹுவே (சோயா தயிர்)"], m: "s", cu: "c", t: ["soy"], r: "tauhuay" },
  { id: "spongecake", c: "snacks", n: ["Plain cake", "原味蛋糕", "Kek kosong", "சாதா கேக்"], m: "s", cu: "x", t: ["egg", "gluten"], r: "ok" },
  { id: "icepop", c: "snacks", n: ["Ice pops", "冰棒", "Aiskrim batang", "ஐஸ் பாப்"], m: "sc", cu: "x", t: [], r: "jelly", mod: ["nored"] },
  { id: "sweets", c: "snacks", n: ["Plain sweets", "原味糖果", "Gula-gula kosong", "சாதா மிட்டாய்"], m: "sc", cu: "x", t: [], r: "ok", mod: ["nored"] },
  { id: "custard", c: "dairy", n: ["Custard", "蛋奶冻", "Kastard", "கஸ்டர்ட்"], m: "s", cu: "w", t: ["dairy", "egg"], r: "dairy", mod: ["smallportion"] },

  // ---------- drinks (low-residue days) ----------
  { id: "kopio", c: "", n: ["Kopi-O / teh-O (no milk)", "咖啡乌 / 茶乌(不加奶)", "Kopi-O / teh-O (tanpa susu)", "கோப்பி-ஓ / தே-ஓ (பால் இல்லாமல்)"], m: "bk", cu: "cmi", t: [], r: "coffeetea" },
  { id: "milo", c: "dairy", n: ["Milo", "美禄", "Milo", "மைலோ"], m: "bk", cu: "x", t: ["gluten", "dairy"], r: "malted", mod: ["nomilkclear"] },
  { id: "milk", c: "dairy", n: ["Milk", "牛奶", "Susu", "பால்"], m: "bk", cu: "x", t: ["dairy"], r: "dairy", mod: ["nomilkclear"] },
  { id: "soymilk", c: "dairy", n: ["Soy milk (strained)", "豆浆(过滤)", "Susu soya (ditapis)", "சோயா பால் (வடிகட்டியது)"], m: "bk", cu: "c", t: ["soy"], r: "soymilk", mod: ["nomilkclear"] },
  { id: "barley", c: "clear", n: ["Strained barley water", "过滤薏米水", "Air barli ditapis", "வடிகட்டிய பார்லி நீர்"], m: "k", cu: "c", t: ["gluten"], r: "ok" },
  { id: "applejuice", c: "fruit", n: ["Strained fruit juice, no pulp (apple, pear, white grape)", "过滤果汁,无果肉(苹果、梨、白葡萄)", "Jus buah ditapis, tanpa pulpa (epal, pear, anggur putih)", "வடிகட்டிய பழச்சாறு, சதை இல்லாமல் (ஆப்பிள், பேரிக்காய், வெள்ளை திராட்சை)"], m: "kc", cu: "x", t: [], r: "juice" },
  { id: "water", c: "clear", n: ["Water", "白开水", "Air kosong", "தண்ணீர்"], m: "kc", cu: "x", t: [], r: "ok" },
  { id: "clearbroth", c: "clear", n: ["Clear broth, strained (chicken/meat)", "过滤清汤(鸡/肉)", "Sup jernih ditapis (ayam/daging)", "வடிகட்டிய தெளிந்த சூப் (கோழி/இறைச்சி)"], m: "kc", cu: "x", t: ["chicken"], r: "ok" },
  { id: "isotonic", c: "clear", n: ["Isotonic / electrolyte drinks", "运动/电解质饮料", "Minuman isotonik / elektrolit", "ஐசோடோனிக் / எலக்ட்ரோலைட் பானங்கள்"], m: "kc", cu: "x", t: [], r: "ok", mod: ["nored"] },
  { id: "sprite", c: "clear", n: ["Colourless soft drinks (Sprite, 7-Up, 100Plus)", "无色汽水(雪碧、七喜、100号)", "Minuman ringan tanpa warna (Sprite, 7-Up, 100Plus)", "நிறமில்லா குளிர்பானம் (ஸ்ப்ரைட், 7-அப், 100பிளஸ்)"], m: "kc", cu: "x", t: [], r: "ok" },
  { id: "honeywater", c: "clear", n: ["Honey", "蜂蜜", "Madu", "தேன்"], m: "kc", cu: "x", t: [], r: "ok" },
  { id: "plainteac", c: "clear", n: ["Plain tea / black coffee (kopi-O, teh-O)", "清茶/黑咖啡(咖啡乌、茶乌)", "Teh / kopi hitam (kopi-O, teh-O)", "வெறும் டீ / கருப்பு காபி (கோப்பி-ஓ, தே-ஓ)"], m: "c", cu: "x", t: [], r: "coffeetea" },

  // ---------- basic items for the category lists (Colonaid Demo) ----------
  { id: "whiterice", c: "grains", n: ["White rice", "白饭", "Nasi putih", "வெள்ளைச் சோறு"], m: "bld", cu: "x", t: [], r: "ok" },
  { id: "whitebread", c: "grains", n: ["White bread", "白面包", "Roti putih", "வெள்ளை ரொட்டி"], m: "bs", cu: "x", t: ["gluten"], r: "ok" },
  { id: "noodles", c: "grains", n: ["Bee hoon (rice vermicelli)", "米粉", "Bihun", "பீஹூன் (அரிசி சேமியா)"], m: "ld", cu: "c", t: [], r: "ok" },
  { id: "eggnoodle", c: "grains", n: ["Egg noodles", "蛋面", "Mi telur", "முட்டை நூடுல்ஸ்"], m: "ld", cu: "cm", t: ["egg", "gluten"], r: "ok" },
  { id: "pasta", c: "grains", n: ["Refined pasta", "精制意大利面", "Pasta ditapis", "சுத்திகரிக்கப்பட்ட பாஸ்தா"], m: "ld", cu: "w", t: ["gluten"], r: "ok" },
  { id: "fish", c: "protein", n: ["Fish", "鱼", "Ikan", "மீன்"], m: "ld", cu: "x", t: ["fish"], r: "ok" },
  { id: "chicken", c: "protein", n: ["Chicken", "鸡肉", "Ayam", "கோழி"], m: "ld", cu: "x", t: ["chicken"], r: "ok" },
  { id: "pork", c: "protein", n: ["Pork", "猪肉", "Daging babi", "பன்றி இறைச்சி"], m: "ld", cu: "c", t: ["pork"], r: "ok" },
  { id: "egg", c: "protein", n: ["Eggs", "鸡蛋", "Telur", "முட்டை"], m: "bld", cu: "x", t: ["egg"], r: "ok" },
  { id: "shellfish", c: "protein", n: ["Prawns / shellfish", "虾/贝类海鲜", "Udang / kerang-kerangan", "இறால் / சிப்பி வகை"], m: "ld", cu: "x", t: ["shellfish"], r: "ok" },
  { id: "tofu", c: "protein", n: ["Tofu (plain)", "豆腐(原味)", "Tauhu (kosong)", "டோஃபு (வெற்று)"], m: "ld", cu: "c", t: ["soy"], r: "ok" },
  { id: "fishball", c: "", n: ["Fish balls or fish cake", "鱼丸或鱼饼", "Bebola ikan atau kek ikan", "மீன் உருண்டை / மீன் கேக்"], m: "ld", cu: "c", t: ["fish"], r: "ok" },
  { id: "cheese", c: "dairy", n: ["Cheese", "奶酪", "Keju", "சீஸ்"], m: "s", cu: "w", t: ["dairy"], r: "dairy", mod: ["smallportion"] },
  { id: "plantmilk", c: "dairy", n: ["Almond or oat milk", "杏仁奶或燕麦奶", "Susu badam atau oat", "பாதாம் / ஓட்ஸ் பால்"], m: "k", cu: "x", t: ["nut", "gluten"], r: "plantmilk" },
  { id: "avocado", c: "fruit", n: ["Small ripe avocado", "小熟牛油果", "Avokado masak kecil", "சிறிய பழுத்த அவகேடோ"], m: "s", cu: "x", t: [], r: "banana" },
  { id: "potato", c: "grains", n: ["Potato (peeled, well-cooked)", "土豆(去皮、煮软)", "Kentang (dikupas, dimasak lembut)", "உருளைக்கிழங்கு (தோல் நீக்கி, நன்கு வேகவைத்து)"], m: "ld", cu: "x", t: [], r: "potato" },
  { id: "chocolate", c: "snacks", n: ["Plain chocolate", "原味巧克力", "Coklat kosong", "சாதா சாக்லேட்"], m: "s", cu: "x", t: ["dairy"], r: "ok" },
  { id: "soysauce", c: "sauces", n: ["Soy sauce / dark soy sauce", "酱油/黑酱油", "Kicap / kicap pekat", "சோயா சாஸ் / கருப்பு சோயா சாஸ்"], m: "", cu: "x", t: ["soy", "gluten"], r: "ok", mod: ["noveg"] },
  { id: "ketchup", c: "sauces", n: ["Ketchup", "番茄酱", "Sos tomato", "கெட்சப்"], m: "", cu: "x", t: [], r: "ok", mod: ["smallportion"] },
  { id: "butter", c: "sauces", n: ["Butter or margarine spread", "牛油或人造牛油", "Mentega atau marjerin", "வெண்ணெய் / மார்கரின்"], m: "", cu: "x", t: ["dairy"], r: "butter" },
  { id: "kaya", c: "sauces", n: ["Kaya (thin spread)", "咖椰(薄涂)", "Kaya (sapuan nipis)", "காயா (மெல்லியதாக)"], m: "", cu: "cm", t: ["egg", "coconut"], r: "kaya" },
  { id: "sugar", c: "sauces", n: ["White sugar", "白糖", "Gula putih", "வெள்ளைச் சீனி"], m: "", cu: "x", t: [], r: "ok" },
  // ---------- dietitian list items (Colonaid Demo diet tab) ----------
  { id: "congee", c: "grains", n: ["White porridge / congee (plain)", "白粥(原味)", "Bubur putih (kosong)", "வெள்ளைக் கஞ்சி (வெற்று)"], m: "bld", cu: "x", t: [], r: "ok" },
  { id: "kwayteownoodle", c: "grains", n: ["Kway teow (flat rice noodles)", "粿条", "Kuey teow", "குவே தியாவ் (தட்டை அரிசி நூடுல்ஸ்)"], m: "ld", cu: "x", t: [], r: "ok" },
  { id: "yellownoodle", c: "grains", n: ["Yellow noodles", "黄面", "Mi kuning", "மஞ்சள் நூடுல்ஸ்"], m: "ld", cu: "x", t: ["egg", "gluten"], r: "ok" },
  { id: "meepok", c: "grains", n: ["Mee pok / mee kia (egg noodles)", "面薄/面仔(蛋面)", "Mee pok / mee kia (mi telur)", "மீ போக் / மீ கியா (முட்டை நூடுல்ஸ்)"], m: "ld", cu: "x", t: ["egg", "gluten"], r: "ok" },
  { id: "meesuanoodle", c: "grains", n: ["Mee sua", "面线", "Mee sua", "மீ சுவா"], m: "ld", cu: "x", t: ["gluten"], r: "ok" },
  { id: "quinoa", c: "grains", n: ["Quinoa, millet, bran", "藜麦、小米、麸皮", "Kuinoa, sekoi, dedak", "கினோவா, தினை, தவிடு"], m: "", cu: "x", t: [], r: "avoid", why: "wholegrain" },
  { id: "wgnoodle", c: "grains", n: ["Wholegrain / high-fibre / buckwheat noodles", "全麦/高纤/荞麦面", "Mi bijirin penuh / tinggi serat / soba", "முழு தானிய / நார்ச்சத்து / பக்வீட் நூடுல்ஸ்"], m: "", cu: "x", t: [], r: "avoid", why: "wholegrain" },
  { id: "leanmeat", c: "protein", n: ["Tender lean meat (well-cooked, cut small)", "嫩瘦肉(煮熟、切小块)", "Daging tanpa lemak yang lembut (dimasak, dipotong kecil)", "மென்மையான கொழுப்பற்ற இறைச்சி (நன்கு வேகவைத்து, சிறிதாக)"], m: "ld", cu: "x", t: ["meat"], r: "ok" },
  { id: "taukwa", c: "protein", n: ["Taukwa (plain)", "豆干(原味)", "Taukwa (kosong)", "தவ்க்வா (வெற்று)"], m: "ld", cu: "x", t: ["soy"], r: "ok" },
  { id: "taupok", c: "protein", n: ["Tau pok (plain)", "豆卜(原味)", "Tau pok (kosong)", "தவ் போக் (வெற்று)"], m: "ld", cu: "x", t: ["soy"], r: "ok" },
  { id: "proteinpowder", c: "protein", n: ["Plant protein powder", "植物蛋白粉", "Serbuk protein tumbuhan", "தாவரப் புரதப் பொடி"], m: "s", cu: "x", t: ["soy"], r: "ok" },
  { id: "supplements", c: "protein", n: ["Nutrition supplements (when needed)", "营养补充品(需要时)", "Suplemen nutrisi (bila perlu)", "ஊட்டச்சத்து சப்ளிமெண்ட் (தேவைப்படும்போது)"], m: "s", cu: "x", t: ["dairy"], r: "ok" },
  { id: "nutbutter", c: "protein", n: ["Smooth nut butter (thin layer, no chunks)", "顺滑坚果酱(薄涂、无颗粒)", "Mentega kacang licin (sapuan nipis, tanpa ketulan)", "மென்மையான கொட்டை வெண்ணெய் (மெல்லியதாக)"], m: "s", cu: "x", t: ["nut"], r: "smoothnut" },
  { id: "beefmutton", c: "protein", n: ["Beef / mutton (red meat)", "牛肉/羊肉(红肉)", "Daging lembu / kambing (daging merah)", "மாட்டிறைச்சி / ஆட்டிறைச்சி (சிவப்பு இறைச்சி)"], m: "", cu: "x", t: ["beef", "mutton", "meat"], r: "redmeat", why: "redmeat" },
  { id: "stuffedtofu", c: "protein", n: ["Tau pok / tofu stuffed with vegetables", "酿蔬菜的豆卜/豆腐", "Tau pok / tauhu disumbat sayur", "காய்கறி அடைத்த தவ் போக் / டோஃபு"], m: "", cu: "x", t: ["soy"], r: "avoid", why: "garnish" },
  { id: "kopic", c: "dairy", n: ["Kopi / teh with milk (kopi-C, teh-C, teh tarik)", "加奶咖啡/茶(咖啡C、茶C、拉茶)", "Kopi / teh susu (kopi-C, teh-C, teh tarik)", "பால் காபி / டீ (கோப்பி-சி, தே-சி, தே தாரிக்)"], m: "k", cu: "x", t: ["dairy"], r: "dairy" },
  { id: "horlicks", c: "dairy", n: ["Horlicks", "好力克", "Horlicks", "ஹார்லிக்ஸ்"], m: "k", cu: "x", t: ["gluten", "dairy"], r: "malted" },
  { id: "icecream", c: "dairy", n: ["Ice cream (plain)", "冰淇淋(原味)", "Aiskrim (kosong)", "ஐஸ்கிரீம் (சாதா)"], m: "s", cu: "x", t: ["dairy"], r: "dairy" },
  { id: "condensed", c: "dairy", n: ["Condensed / evaporated milk", "炼乳/淡奶", "Susu pekat / susu cair", "கண்டென்ஸ்டு / எவாப்பரேட்டட் பால்"], m: "k", cu: "x", t: ["dairy"], r: "dairy" },
  { id: "flavdairy", c: "dairy", n: ["Flavoured / fruit / nut dairy", "调味/水果/坚果奶制品", "Tenusu berperisa / buah / kacang", "சுவையூட்டிய / பழ / கொட்டை பால் பொருட்கள்"], m: "", cu: "x", t: ["dairy"], r: "avoid", why: "fruitveg" },
  { id: "coconut", c: "fruit", n: ["Coconut (flesh)", "椰肉", "Isi kelapa", "தேங்காய் (சதை)"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "rawveg", c: "veg", n: ["Raw vegetables and salads", "生菜和沙拉", "Sayur mentah dan salad", "பச்சைக் காய்கறிகள், சாலட்"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "corn", c: "veg", n: ["Corn", "玉米", "Jagung", "சோளம்"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "beansprout", c: "veg", n: ["Bean sprouts", "豆芽", "Taugeh", "முளைப்பயறு"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "vegskins", c: "veg", n: ["Vegetable skins and seeds", "蔬菜皮和籽", "Kulit dan biji sayur", "காய்கறித் தோல், விதைகள்"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "aromatics", c: "veg", n: ["Onion, garlic, ginger, lemongrass in visible pieces", "看得见的洋葱、蒜、姜、香茅块", "Bawang, bawang putih, halia, serai dalam cebisan yang kelihatan", "கண்ணுக்குத் தெரியும் வெங்காயம், பூண்டு, இஞ்சி, எலுமிச்சைப்புல் துண்டுகள்"], m: "", cu: "x", t: [], r: "avoid", why: "garnish" },
  { id: "gelatin", c: "snacks", n: ["Gelatin jelly (clear, no fruit pieces)", "明胶果冻(透明、无果粒)", "Jeli gelatin (jernih, tanpa buah)", "ஜெலட்டின் ஜெல்லி (தெளிவான, பழத் துண்டு இல்லாமல்)"], m: "sc", cu: "x", t: [], r: "jelly" },
  { id: "dessertsoup", c: "snacks", n: ["Strained dessert soup", "过滤糖水", "Sup pencuci mulut ditapis", "வடிகட்டிய இனிப்பு சூப்"], m: "s", cu: "x", t: [], r: "ok" },
  { id: "sorbet", c: "snacks", n: ["Sorbet", "雪葩", "Sorbet", "சர்பெட்"], m: "sc", cu: "x", t: [], r: "jelly" },
  { id: "fruitdessert", c: "snacks", n: ["Desserts with fruit, nuts, seeds, wholegrain or coconut", "含水果、坚果、种子、全谷或椰子的甜点", "Pencuci mulut dengan buah, kacang, biji, bijirin penuh atau kelapa", "பழம், கொட்டை, விதை, முழு தானியம், தேங்காய் உள்ள இனிப்புகள்"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "oystersauce", c: "sauces", n: ["Oyster sauce", "蚝油", "Sos tiram", "ஆய்ஸ்டர் சாஸ்"], m: "", cu: "x", t: [], r: "ok" },
  { id: "mayo", c: "sauces", n: ["Mayonnaise", "蛋黄酱", "Mayonis", "மயோனைஸ்"], m: "", cu: "x", t: ["egg"], r: "ok" },
  { id: "vegbroth", c: "clear", n: ["Clear broth, strained (vegetable)", "过滤清汤(蔬菜)", "Sup jernih ditapis (sayur)", "வடிகட்டிய தெளிந்த சூப் (காய்கறி)"], m: "kc", cu: "x", t: [], r: "ok" },
  // ---------- avoid (for "Can I eat this?") ----------
  { id: "glucosewater", c: "clear", n: ["Glucose water", "葡萄糖水", "Air glukosa", "குளுக்கோஸ் நீர்"], m: "kc", cu: "x", t: [], r: "ok" },
  { id: "yam", c: "grains", n: ["Sweet potato / yam (peeled, well-cooked)", "番薯/芋头(去皮、煮软)", "Keledek / keladi (dikupas, dimasak lembut)", "சர்க்கரைவள்ளி / சேப்பங்கிழங்கு (தோல் நீக்கி)"], m: "ld", cu: "cmi", t: [], r: "potato" },
  { id: "duck", c: "protein", n: ["Duck (roast or braised)", "鸭肉(烧鸭、卤鸭)", "Itik (panggang atau rebus)", "வாத்து இறைச்சி"], m: "", cu: "c", t: ["meat"], r: "avoid", why: "redmeat" },
  { id: "brownrice", c: "grains", n: ["Brown / red rice", "糙米/红米", "Nasi perang / beras merah", "பழுப்பு / சிவப்பு அரிசி"], m: "", cu: "x", t: [], r: "avoid", why: "wholegrain" },
  { id: "wholemeal", c: "grains", n: ["Wholemeal / wholegrain bread and biscuits", "全麦面包和饼干", "Roti dan biskut mil penuh", "முழு கோதுமை ரொட்டி, பிஸ்கட்"], m: "", cu: "x", t: [], r: "avoid", why: "wholegrain" },
  { id: "oats", c: "grains", n: ["Oats, muesli, granola", "燕麦、什锦麦片", "Oat, muesli, granola", "ஓட்ஸ், மியூஸ்லி"], m: "", cu: "x", t: [], r: "avoid", why: "wholegrain" },
  { id: "chapati", c: "grains", n: ["Chapati, wholemeal naan", "印度全麦薄饼、全麦馕", "Capati, naan mil penuh", "சப்பாத்தி, முழு கோதுமை நான்"], m: "", cu: "i", t: [], r: "avoid", why: "wholegrain" },
  { id: "dal", c: "protein", n: ["Beans, lentils, dal", "豆类、扁豆", "Kekacang, kacang dal", "பீன்ஸ், பருப்பு"], m: "", cu: "i", t: [], r: "avoid", why: "legume" },
  { id: "vadai", c: "grains", n: ["Vadai", "印度炸豆饼 Vadai", "Vadai", "வடை"], m: "", cu: "i", t: [], r: "avoid", why: "legume" },
  { id: "laksa", c: "local", n: ["Laksa", "叻沙", "Laksa", "லக்சா"], m: "", cu: "cm", t: [], r: "avoid", why: "laksa" },
  { id: "nasilemak", c: "local", n: ["Nasi lemak", "椰浆饭", "Nasi lemak", "நாசி லெமாக்"], m: "", cu: "m", t: [], r: "avoid", why: "nasilemak" },
  { id: "rendang", c: "local", n: ["Beef rendang, mutton curry", "仁当牛肉、羊肉咖喱", "Rendang daging, kari kambing", "மாட்டிறைச்சி ரெண்டாங், ஆட்டுக்கறி"], m: "", cu: "mi", t: ["meat"], r: "avoid", why: "redmeat" },
  { id: "satay", c: "local", n: ["Satay with peanut sauce", "沙爹配花生酱", "Sate dengan kuah kacang", "சாதே (வேர்க்கடலை சாஸ்)"], m: "", cu: "m", t: ["meat"], r: "avoid", why: "nuts" },
  { id: "friedchicken", c: "protein", n: ["Tough / deep-fried meat", "肉质硬或油炸的肉", "Daging liat / goreng", "கடினமான / பொரித்த இறைச்சி"], m: "", cu: "x", t: ["meat"], r: "avoid", why: "fried" },
  { id: "sausage", c: "protein", n: ["Sausage, lap cheong, salami (processed meat)", "香肠、腊肠、萨拉米(加工肉)", "Sosej, lap cheong, salami (daging diproses)", "சாசேஜ், லாப் சியோங், சலாமி (பதப்படுத்திய இறைச்சி)"], m: "", cu: "x", t: ["meat"], r: "avoid", why: "processed" },
  { id: "tempeh", c: "protein", n: ["Tempeh", "天贝", "Tempe", "டெம்பே"], m: "", cu: "m", t: [], r: "avoid", why: "legume" },
  { id: "nuts", c: "protein", n: ["Nuts and seeds (whole/chunky)", "坚果和种子(整颗/颗粒)", "Kacang dan biji (utuh/berketul)", "கொட்டைகள், விதைகள் (முழுதாக)"], m: "", cu: "x", t: [], r: "avoid", why: "nuts" },
  { id: "fruit", c: "fruit", n: ["Fruit with skin, seeds or pulp", "带皮、籽或果肉的水果", "Buah berkulit, berbiji atau berpulpa", "தோல், விதை, சதையுள்ள பழங்கள்"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "leafy", c: "veg", n: ["Leafy greens (kailan, spinach, chye sim)", "绿叶菜(芥兰、菠菜、菜心)", "Sayur berdaun (kailan, bayam, sawi)", "கீரை வகைகள் (கைலான், பசலை, சாய் சிம்)"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "driedfruit", c: "fruit", n: ["Dried fruit", "果干", "Buah kering", "உலர் பழங்கள்"], m: "", cu: "x", t: [], r: "avoid", why: "fruitveg" },
  { id: "chilli", c: "sauces", n: ["Chilli, sambal, chilli sauces", "辣椒、参巴酱、辣椒酱", "Cili, sambal, sos cili", "மிளகாய், சம்பல், மிளகாய் சாஸ்"], m: "", cu: "x", t: [], r: "avoid", why: "seeds" },
  { id: "garnish", c: "sauces", n: ["Garnishes: fried shallots, spring onion, coriander", "配料:炸葱头、葱、香菜", "Hiasan: bawang goreng, daun bawang, daun ketumbar", "அலங்காரம்: பொரித்த வெங்காயம், வெங்காயத்தாள், கொத்தமல்லி"], m: "", cu: "x", t: [], r: "avoid", why: "garnish" },
  { id: "redjelly", c: "snacks", n: ["Red, purple or blue jelly, drinks or sweets", "红色、紫色或蓝色果冻/饮料/糖果", "Jeli, minuman atau gula-gula merah, ungu atau biru", "சிவப்பு / ஊதா / நீல ஜெல்லி, பானம்"], m: "", cu: "x", t: [], r: "avoid", why: "colour" },
  { id: "prune", c: "fruit", n: ["Prune juice", "西梅汁", "Jus prun", "ப்ரூன் சாறு"], m: "", cu: "x", t: [], r: "avoid", why: "colourfibre" },
  { id: "pulpjuice", c: "fruit", n: ["Orange, tomato, sugarcane, calamansi juice", "橙汁、番茄汁、甘蔗水、酸柑汁", "Jus oren, tomato, tebu, limau kasturi", "ஆரஞ்சு, தக்காளி, கரும்பு, கலமான்சி சாறு"], m: "", cu: "x", t: [], r: "avoid", why: "pulp" },
  { id: "cendol", c: "local", n: ["Cendol, ice kachang, bubur cha cha", "煎蕊、红豆冰、摩摩喳喳", "Cendol, ais kacang, bubur cha cha", "செண்டோல், ஐஸ் கச்சாங்"], m: "", cu: "cm", t: [], r: "avoid", why: "cendol" },
  { id: "alcohol", c: "clear", n: ["Alcohol (beer, wine)", "酒(啤酒、葡萄酒)", "Alkohol (bir, wain)", "மது (பீர், ஒயின்)"], m: "", cu: "x", t: [], r: "avoid", why: "alcohol" },
  { id: "prata", c: "grains", n: ["Roti prata (plain, white sugar only)", "原味印度煎饼(只配白糖)", "Roti prata kosong (gula putih sahaja)", "வெற்று ரொட்டி பிராட்டா (வெள்ளைச் சீனி மட்டும்)"], m: "bs", cu: "im", t: ["gluten"], r: "prata", mod: ["whitesugar"] },
  { id: "meesoto", c: "local", n: ["Mee soto (no vegetables or garnish)", "马来鸡汤面(不要蔬菜和配料)", "Mee soto (tanpa sayur atau hiasan)", "மீ சோட்டோ (காய்கறி, அலங்காரம் இல்லாமல்)"], m: "", cu: "m", t: [], r: "sotomod", mod: ["nobeansprout", "nogarnish"] }
];

/* keywords (any language) → food id, for the "Can I eat this?" search */
window.CA_FOOD_ALIASES = {
  "kopi": "kopio", "teh": "kopio", "coffee": "kopio", "tea": "kopio", "咖啡": "kopio", "茶": "kopio", "காபி": "kopio", "டீ": "kopio",
  "horlicks": "milo", "美禄": "milo", "மைலோ": "milo",
  "milk": "milk", "牛奶": "milk", "susu": "milk", "பால்": "milk", "teh tarik": "milk", "cheese": "cheese", "keju": "cheese", "奶酪": "cheese",
  "yogurt": "yoghurt", "酸奶": "yoghurt", "dadih": "yoghurt", "தயிர்": "yoghurt",
  "egg": "egg", "telur": "egg", "蛋": "egg", "முட்டை": "egg",
  "rice": "whiterice", "nasi": "chickenporridgemalay", "饭": "whiterice", "சோறு": "whiterice",
  "porridge": "fishcongee", "congee": "fishcongee", "粥": "fishcongee", "bubur": "chickencongee", "கஞ்சி": "fishcongee",
  "bread": "whitebread", "roti": "whitebread", "面包": "whitebread", "ரொட்டி": "whitebread",
  "noodle": "eggnoodle", "mee": "noodlesoup", "面": "noodlesoup", "bee hoon": "noodles", "beehoon": "noodles", "bihun": "noodles", "米粉": "noodles",
  "potato": "potato", "kentang": "potato", "土豆": "potato", "உருளை": "potato",
  "tofu": "tofu", "tauhu": "tofu", "豆腐": "tofu", "taukwa": "tofu", "tau pok": "tofu", "டோஃபு": "tofu",
  "beef": "leanbeef", "lembu": "leanbeef", "牛肉": "leanbeef", "mutton": "rendang", "kambing": "rendang", "羊肉": "rendang",
  "chicken": "chicken", "ayam": "chickenrice", "鸡": "chickenrice", "கோழி": "chickenrice",
  "fish": "fish", "ikan": "fish", "鱼": "fish", "மீன்": "fish",
  "prawn": "shellfish", "udang": "shellfish", "虾": "shellfish", "இறால்": "prawnbeehoon",
  "pork": "pork", "猪肉": "pork",
  "soy milk": "soymilk", "豆浆": "soymilk", "susu soya": "soymilk",
  "juice": "applejuice", "jus": "applejuice", "果汁": "applejuice", "சாறு": "applejuice",
  "jelly": "jelly", "agar": "jelly", "果冻": "jelly", "ஜெல்லி": "jelly",
  "vegetable": "leafy", "veg": "leafy", "sayur": "leafy", "蔬菜": "leafy", "காய்கறி": "leafy", "carrot": "cookedveg",
  "fruit": "fruit", "buah": "fruit", "水果": "fruit", "பழம்": "fruit", "apple": "fruit", "papaya": "fruit", "watermelon": "fruit",
  "peanut butter": "pbtoast", "花生酱": "pbtoast", "peanut": "nuts", "花生": "nuts", "kacang": "nuts",
  "sambal": "chilli", "辣椒": "chilli", "cili": "chilli", "மிளகாய்": "chilli",
  "idly": "idli", "dosa": "thosai", "dosai": "thosai", "தோசை": "thosai", "இட்லி": "idli", "iddiyappam": "putumayam", "idiyappam": "putumayam",
  "curry": "rendang", "kari": "rendang", "咖喱": "rendang", "கறி": "rendang",
  "sprite": "sprite", "7up": "sprite", "7-up": "sprite", "soda": "sprite",
  "100 plus": "isotonic", "100plus": "isotonic", "pocari": "isotonic", "gatorade": "isotonic",
  "ice cream": "custard", "aiskrim": "custard", "冰淇淋": "custard",
  "sweet potato": "potatofish", "yam": "potatofish", "keledek": "potatofish",
  "fishball": "fishball", "fish ball": "fishball", "鱼丸": "fishball",
  "beer": "alcohol", "wine": "alcohol", "啤酒": "alcohol",
  "canai": "prata", "congee": "congee", "porridge": "congee", "kway teow": "kwayteownoodle", "粿条": "kwayteownoodle", "mee pok": "meepok", "mee kia": "meepok", "yellow noodle": "yellownoodle", "mee sua": "meesuanoodle", "面线": "meesuanoodle", "taukwa": "taukwa", "豆干": "taukwa", "tau pok": "taupok", "豆卜": "taupok", "corn": "corn", "玉米": "corn", "jagung": "corn", "bean sprout": "beansprout", "taugeh": "beansprout", "豆芽": "beansprout", "beef": "beefmutton", "mutton": "beefmutton", "牛肉": "beefmutton", "羊肉": "beefmutton", "horlicks": "horlicks", "好力克": "horlicks", "kopi c": "kopic", "kopi-c": "kopic", "teh tarik": "kopic", "拉茶": "kopic", "ice cream": "icecream", "冰淇淋": "icecream", "aiskrim": "icecream", "condensed milk": "condensed", "evaporated milk": "condensed", "炼乳": "condensed", "coconut": "coconut", "椰": "coconut", "kelapa": "coconut", "sorbet": "sorbet", "gelatin": "gelatin", "oyster sauce": "oystersauce", "蚝油": "oystersauce", "mayo": "mayo", "mayonnaise": "mayo", "quinoa": "quinoa", "buckwheat": "wgnoodle", "soba": "wgnoodle", "garlic": "aromatics", "onion": "aromatics", "ginger": "aromatics", "蒜": "aromatics", "salad": "rawveg", "tempe": "tempeh", "pasta": "pasta", "spaghetti": "pasta", "soy sauce": "soysauce", "kicap": "soysauce", "酱油": "soysauce", "oyster sauce": "soysauce", "ketchup": "ketchup", "mayo": "ketchup", "butter": "butter", "mentega": "butter", "牛油": "butter", "margarine": "butter", "kaya": "kaya", "咖椰": "kaya", "sugar": "sugar", "gula": "sugar", "糖": "sugar", "chocolate": "chocolate", "coklat": "chocolate", "巧克力": "chocolate", "avocado": "avocado", "牛油果": "avocado", "seafood": "shellfish", "海鲜": "shellfish", "yellow noodle": "eggnoodle", "mee kia": "eggnoodle", "mee pok": "eggnoodle", "fish cake": "fishball", "prata": "prata", "ovaltine": "milo", "阿华田": "milo", "glucose": "glucosewater", "葡萄糖": "glucosewater", "duck": "duck", "itik": "duck", "鸭": "duck", "taro": "yam", "芋头": "yam", "番薯": "yam", "mee sua": "meesua", "面线": "meesua", "misua": "meesua", "kway teow": "kwayteow", "粿条": "kwayteow", "almond milk": "plantmilk", "oat milk": "plantmilk", "goat milk": "milk",
  "soup": "clearbroth", "broth": "clearbroth", "clear soup": "clearbroth", "清汤": "clearbroth", "sup": "clearbroth", "toast": "whitebread", "ice cube": "water", "雪碧": "sprite", "七喜": "sprite"
};
